# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

scale_rcpp <- function(X, a, b) {
    invisible(.Call('_simxQTL_scale_rcpp', PACKAGE = 'simxQTL', X, a, b))
}

